baseURL = 'https://kimbeomgyu.github.io'
languageCode = 'ko-KR'
title = 'kimbeomgyu'
description = '반갑습니다. 개발자 김범규 블로그입니다.'
theme = 'PaperMod'
copyright = "[kimbeomgyu](https://github.com/kimbeomgyu) © All rights reserved."
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
paginate = 15
pygmentsUseClasses = true
keywords = ['backend', 'frontend', 'developer', 'web', 'blog', 'personal', 'portfolio', 'resume', 'projects', 'articles', 'about', 'contact', 'kimbeomgyu']
googleAnalytics = 'G-J9DBNPBFH8'

[minify]
disableXML = true
minifyOutput = true

[services]
  [services.disqus]
    shortname = 'kimbeomgyu'

[menus]
  [[menus.main]]
    name = 'Articles'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About me'
    pageRef = '/pages/about'
    weight = 20
  [[menus.main]]
    name = 'Projects'
    pageRef = '/pages/projects'
    weight = 30

[params]
  # code copy button on
  ShowCodeCopyButtons = true
  env = "production"
  comments = true
